inmobiliaria/urls.py
from django.contrib import admin
from django.urls import path, include
from web.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('registro/', registro_usuario, name='registro_usuario'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inmueble/<int:id>/',detalle_inmueble , name='detalle'),
    path('inmuebles/<int:id>/generar-solicitud/', generar_solicitud_arriendo, name='generar_solicitud_arriendo'),
    path('inmueble/<int:id>/editar_inmueble',actualizar_inmueble, name='editar_inmueble'),
    path('inmueble/<int:id>/eliminar_inmueble',eliminar_inmueble, name='eliminar_inmueble'),
    path('alta-inmueble/', crear_inmueble, name='alta_inmueble'),
    path('solicitudes/', solicitudes_arrendador, name='solicitudes_arrendador'),
    path('dashboard/', dashboard, name='dashboard'),
    path('perfil/', actualizar_usuario, name='actualizar_usuario'),
    path('cambiar_estado_solicitud/<int:solicitud_id>/', cambiar_estado_solicitud, name='cambiar_estado_solicitud'),
    path('cancelar_solicitud/<int:solicitud_id>/', cancelar_solicitud, name='cancelar_solicitud'),
    path('comunas/', comunas, name='comunas'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Region(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre


class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre


class Usuario(AbstractUser):
    TIPO_USUARIO_CHOICES = [
        ('arrendatario', 'Arrendatario'),
        ('arrendador', 'Arrendador'),
    ]
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    rut = models.CharField(max_length=10, unique=True)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=13)
    tipo_usuario = models.CharField(max_length=20, choices=TIPO_USUARIO_CHOICES)
    correo_electronico = models.EmailField(unique=True, default='correo@correo.cl')

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"


class Inmueble(models.Model):
    TIPO_INMUEBLE_CHOISES = [
        ('casa','Casa'),
        ('departamento','Departamento'),
        ('parcela','Parcela'),
    ]
    nombre=models.CharField(max_length=50)
    direccion=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=250)
    imagen = models.ImageField(upload_to='',null=True, blank=True)
    precio = models.DecimalField(max_digits=10, decimal_places=0)
    comuna = models.ForeignKey(Comuna, related_name='inmuebles', on_delete=models.CASCADE)
    disponible=models.BooleanField(default=True)
    m2_construidos = models.DecimalField(max_digits=10, decimal_places=2)
    m2_terreno = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_estacionamientos = models.PositiveIntegerField()
    cantidad_habitaciones = models.PositiveIntegerField()
    cantidad_banos = models.PositiveIntegerField()
    tipo_de_inmueble=models.CharField(max_length=12, choices=TIPO_INMUEBLE_CHOISES)
    propietario = models.ForeignKey(Usuario, on_delete=models.CASCADE)


    def __str__(self) -> str:
        return f"{self.nombre}"


class SolicitudArriendo(models.Model):
    TIPO_ESTADO_CHOISES = [
        ('pendiente','Pendiente'),
        ('aceptado','Aceptado'),
        ('rechazado','Rechazado'),
    ]

    arrendatario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    inmueble = models.ForeignKey(Inmueble, on_delete=models.CASCADE)
    mensaje = models.TextField(blank=True)
    estado =models.CharField( max_length=10, choices=TIPO_ESTADO_CHOISES, default='pendiente')

    def __str__(self):
        return f"Solicitud de {self.inmueble.nombre} \n por {self.arrendatario.nombres} {self.arrendatario.apellidos}"

web/templates/alta_inmueble.html
{% extends 'base.html' %}

{% block title %}Crear Inmueble{% endblock %}

{% block content %}

<div class="container">

    <div class="text-center my-3">
        <h2>Alta de Inmueble</h2>
    </div>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="nombre" class="form-label">Nombre</label>
            <input type="text" class="form-control" id="nombre" name="nombre">
        </div>

        <div class="mb-3">
            <label for="direccion" class="form-label">Dirección</label>
            <input type="text" class="form-control" id="direccion" name="direccion">
        </div>

        <div class="mb-3">
            <label for="descripcion" class="form-label">Descripción</label>
            <textarea class="form-control" id="descripcion" name="descripcion" rows="3"></textarea>
            <!--input type="text" class="form-control" id="descripcion" name="descripcion"-->
        </div>

        <div class="mb-3">
            <label for="imagen" class="form-label">Imágen</label>
            <input class="form-control" type="file" id="imagen" name="imagen">
        </div>

        <div class="mb-3">

            <div class="row">

                <div class="col-12 col-md-6">

                    <label for="region" class="form-label">Region</label>
                    <select class="form-select" aria-label="Region select" id="region" name="region" onchange="loadComunas()">
                        <option value="0" selected>Region</option>
                        {% for region in regiones %}
                            <option value="{{ region.id }}">{{ region.nombre }}</option>
                        {% endfor %}
                    </select>

                </div>

                <div class="col-12 col-md-6">

                    <label for="comuna" class="form-label">Comuna</label>
                    <select class="form-select" aria-label="Comuna select" id="comuna" name="comuna">
                        <option value="0" selected>Comuna</option>
                        {% for comuna in comunas %}
                            <option value="{{ comuna.id }}">{{ comuna.nombre }}</option>
                        {% endfor %}
                    </select>

                </div>

            </div>

        </div>

        <div class="mb-3">

            <div class="row">

                <div class="col-12 col-md-6">
                    <label for="m2_construidos" class="form-label">M2 Construidos</label>
                    <input type="text" class="form-control" id="m2_construidos" name="m2_construidos">
                </div>

                <div class="col-12 col-md-6">
                    <label for="m2_terreno" class="form-label">M2 Terreno</label>
                    <input type="text" class="form-control" id="m2_terreno" name="m2_terreno">
                </div>

            </div>
        </div>

        <div class="mb-3">

            <div class="row">

                <div class="col-12 col-md-4">
                    <label for="cantidad_estacionamientos" class="form-label">Cantidad Estacionamientos</label>
                    <input type="text" class="form-control" id="cantidad_estacionamientos" name="cantidad_estacionamientos">
                </div>

                <div class="col-12 col-md-4">
                    <label for="cantidad_habitaciones" class="form-label">Cantidad Habitaciones</label>
                    <input type="text" class="form-control" id="cantidad_habitaciones" name="cantidad_habitaciones">
                </div>

                <div class="col-12 col-md-4">
                    <label for="cantidad_banos" class="form-label">Cantidad Baños</label>
                    <input type="text" class="form-control" id="cantidad_banos" name="cantidad_banos">
                </div>

            </div>

        </div>

        <div class="mb-3">

            <div class="row">

                <div class="col-12 col-md-4">
                    <label for="tipo_de_inmueble" class="form-label">Tipo de Inmueble</label>
                    <select class="mb-3 form-select" aria-label="Tipo de Inmueble select" id="tipo_de_inmueble" name="tipo_de_inmueble">
                        <option selected>Tipo de Inmueble</option>
                        <option value="casa">Casa</option>
                        <option value="departamento">Departamento</option>
                        <option value="parcela">Parcela</option>
                    </select>
                </div>

                <div class="col-12 col-md-4">
                    <label for="precio" class="form-label">Precio</label>
                    <input type="text" class="form-control" id="precio" name="precio">
                </div>

                <div class="col-12 col-md-4 form-check pt-5">
                    <input type="checkbox" class="form-check-input" id="disponible" name="disponible" checked>
                    <label class="form-check-label" for="disponible">Disponible</label>
                </div>

            </div>

        </div>

        <div class="d-inline-row">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a class="btn btn-secondary" href="{% url 'dashboard' %}">Volver</a>
        </div>
    </form>

</div>

<!-- <script>

    function getCookie(name) {

        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        //RETORNANDO EL TOKEN
        return cookieValue;
  
    }//end function getCookie

    function loadComunas() {
        let region_id = $('#region').val();
        let csrftoken = getCookie('csrftoken');
        if (region_id !== '0') {
            $.ajax({
                type: 'POST',
                url: '{% url 'alta_inmueble' %}',
                data: {csrfmiddlewaretoken: csrftoken,'region_id': region_id},
                success: function (data) {
                }
            });
        }
    }

</script> -->

{% endblock %}

web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
     <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-villa-agency.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
 <!--
    {% static 'vendor/bootstrap/css/bootstrap.min.css' %}
    <!-- Agregar aquí tus enlaces a archivos CSS externos, fuentes, etc. -->
</head>

<body>
{% include "includes/preloader.html" %}

{% block 'header' %}
{% include "includes/header.html" %}
{% endblock 'header' %}

<main >
    {% block content %}
    {% endblock %}
</main>


{% block footer %}
{% include "includes/footer.html" %}
{% endblock footer %}


{% include "includes/scripts.html" %}

</body>
</html>

web/templates/dashboard_arrendador.html
{% extends "base.html" %}
{% block content %}
  {% if user.tipo_usuario == 'arrendador' %}

  <div class="text-center mb-3">
    <h2>Tus Inmuebles</h2> 
  </div>
  <section class="container mx-auto pt-5">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
      {% for inm in inmuebles %}
        <div class="col">
          <div class="card h-100">
              <img class="card-img-top" src="/media/{{inm.imagen}}" alt="Card image cap">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{ inm.nombre }}</h5>
              <div class="alert {% if inm.disponible %}alert-success{% else %}alert-danger{% endif %}">
                <p>Estado: {% if inm.disponible %}Disponible{% else %}No disponible{% endif %}</p>
              </div>
              <p class="card-text text-justify">
                  {% if inm.descripcion|length > 100 %}
                      {{ inm.descripcion|slice:":100" }}... <a href="">descripcion</a>
                  {% else %}
                      {{ inm.descripcion}}
                  {% endif %}
              </p>
          </div>
            <div class="card-footer">
              <a class="btn btn-primary" href="{% url 'detalle' inm.id %}">Detalles</a>
              <a class="btn btn-danger" href="{% url 'eliminar_inmueble' inm.id %}" onclick="return confirm('¿Seguro que quieres eliminar este inmueble?');">Eliminar</a>
            </div>
          </div>
        </div>
      {% endfor %}  
    </div>
  </section>

  <div class="text-center my-4">
     <h2>Solicitudes Recibidas</h2>
  </div>
  
  <section class="container mx-auto pt-5">
      <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
          {% for solicitud in solicitudes_recibidas %}
          <div class="card text-bg-tertiary mb-3" style="max-width: 18rem;">
                  <div class="card-header alert alert-warning mt-2">{{solicitud.estado}}</div>
                  <div class="card-body">
                      <h6 class="card-title">{{ solicitud }}</h6>
                      <p class="mb-3">{{solicitud.mensaje}}</p>
                      {% if solicitud.estado != 'aceptado' %}
                          <form method="post" action="{% url 'cambiar_estado_solicitud' solicitud.id %}">
                              {% csrf_token %}
                              <select class="form-select" name="nuevo_estado">
                                  <option value="pendiente">Pendiente</option>
                                  <option value="aceptado">Aceptado</option>
                                  <option value="rechazado">Rechazado</option>
                              </select>
                              <button class="btn btn-success mt-3" type="submit">Cambiar Estado</button>
                          </form>
                      {% endif %}
                  </div>
              </div>
          {% endfor %}
      </div>
  </section>
  {% endif %}
{% endblock %}

web/templates/dashboard_arrendatario.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <div class="text-center my-3">
    <h2>Dashboard - Arrendatario</h2>
  </div>

  <div class="container mb-5 mx-auto">

    <form class="row g-3" method="GET" action="{% url 'dashboard' %}">
      <div class="col-auto">
        <label for="region" class="visually-hidden">Región:</label>
        <select class="form-control" name="region" id="region">
          <option value="0">Seleccionar Región</option>
          {% for region in regiones %}
            <option value="{{ region.id }}">{{ region.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-auto">
        <label for="comuna" class="visually-hidden">Comuna:</label>
        <select class="form-control" name="comuna" id="comuna">
          <option value="0">Seleccionar Comuna</option>
          {% for comuna in comunas %}
            <option value="{{ comuna.id }}">{{ comuna.nombre }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="col-auto">
        <button class="btn btn-primary" type="submit">Filtrar</button>
      </div>
    </form>

  </div>

  <div class="text-center mb-3">
    <h3>Inmuebles Disponibles:</h3>
  </div>

  <ul>
    <section class="container mx-auto pt-5">
      <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
        {% for inm in inmuebles %}
          <div class="col">
            <div class="card h-100">
                <img class="card-img-top" src="/media/{{inm.imagen}}" alt="Card image cap">
              </a>
              <div class="card-body">
                <h5 class="card-title">
                  <span class="p-1 me-2 text-primary bg-primary-subtle border border-primary-subtle rounded-3">
                    {{ inm.tipo_de_inmueble }}
                  </span><hr>
                  {{ inm.nombre }}
                </h5>
                <p class="card-text text-justify">
                    {% if inm.descripcion|length > 50 %}
                        {{ inm.descripcion|slice:":50" }}... <a href="">descripcion</a>
                    {% else %}
                        {{ inm.descripcion}}
                    {% endif %}
                </p>
              </div>
              <div class="card-footer">
                <a class="btn btn-primary" href="{% url 'detalle' inm.id %}">Detalles</a>
                <a class="btn btn-success" href="{% url 'generar_solicitud_arriendo' inm.id %}">Solicitar Arriendo</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </section>
  </ul>

  <div class="text-center my-4 pt-4">
    <h3>Mis Solicitudes de Arriendo:</h3>
  </div>

  <section class="container mx-auto pt-5">

    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">

      {% for solicitud in solicitudes %}
        <!---Inicio Div Card-->
        <div class="card mb-3" style="max-width: 18rem;">
        <!---Fin Div Card (declaración de clases)-->

          <div class="card-header mt-2
            {% if solicitud.estado == 'aceptado' %}bg-success
            {% elif solicitud.estado == 'pendiente' %}bg-warning
            {% elif solicitud.estado == 'rechazado' %}bg-danger
            {% else %}bg-secondary{% endif %}
          ">
            {{solicitud.estado}}
          </div>

          <div class="card-body">
            <h5 class="card-title">{{ solicitud }}</h5>
            <P>{{solicitud.mensaje}}</P>
          </div>

          <div class="card-footer">
            <form action="{% url 'cancelar_solicitud' solicitud.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger" {% if solicitud.estado != 'pendiente' %}disabled{% endif %}>Cancelar Solicitud</button>
            </form>
          </div>

        </div> <!---Fin Div Card-->
      {% endfor %}

    </div>

  </section>

{% endblock %}

web/templates/editar_inmueble.html
{% extends "base.html" %}

{% block title %}Editar Inmueble{% endblock %}

{% block content %}

    <div class="text-center my-4">
        <h2>Editar Inmueble</h2>
    </div>

    <div class="container">

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_nombre" class="form-label">Nombre</label>
                <input type="text" class="form-control" id="id_nombre" name="nombre" value="{{form.nombre.value}}">
            </div>

            <div class="mb-3">
                <label for="id_direccion" class="form-label">Dirección</label>
                <input type="text" class="form-control" id="id_direccion" name="direccion" value="{{form.direccion.value}}">
            </div>

            <div class="mb-3">
                <label for="id_descripcion" class="form-label">Descripción</label>
                <textarea class="form-control" id="id_descripcion" name="descripcion" rows="3">{{form.descripcion.value}}</textarea>
                <!--input type="text" class="form-control" id="descripcion" name="descripcion"-->
            </div>

            <div class="mb-3">

                <div class="row">

                    <div class="col-12 col-md-8">

                        <label for="id_imagen" class="form-label">Imágen</label>
                        <input class="form-control" type="file" id="id_imagen" name="imagen">

                    </div>

                    <div class="col-12 col-md-2">
                        <img src="/media/{{form.imagen.value}}" width="10px">
                    </div>

                    <div class="col-12 col-md-2">
                        <input type="checkbox" class="form-check-input" id="id_eliminar_imagen" name="eliminar_imagen">
                        <label class="form-check-label" for="id_eliminar_imagen">Eliminar</label>
                    </div>

                </div>
            </div>

            <div class="mb-3">

                <div class="row">

                    <div class="col-12 col-md-6">

                        <label for="id_region" class="form-label">Region</label>
                        <select class="form-select" aria-label="Region select" id="id_region" name="region">
                            <option value="0" selected>Region</option>
                            {% for region in regiones %}
                                <option value="{{ region.id }}">{{ region.nombre }}</option>
                            {% endfor %}
                        </select>

                    </div>

                    <div class="col-12 col-md-6">

                        <label for="id_comuna" class="form-label">Comuna</label>
                        <select class="form-select" aria-label="Comuna select" id="id_comuna" name="comuna">
                            <option value="0" selected>Comuna</option>
                            {% for comuna in comunas %}
                                <option value="{{ comuna.id }}" {% if comuna.id == form.comuna.value %} selected{% endif %}>{{ comuna.nombre }}</option>
                            {% endfor %}
                        </select>

                    </div>

                </div>

            </div>

            <div class="mb-3">

                <div class="row">

                    <div class="col-12 col-md-6">
                        <label for="id_m2_construidos" class="form-label">M2 Construidos</label>
                        <input type="text" class="form-control" id="id_m2_construidos" name="m2_construidos" value="{{form.m2_construidos.value}}">
                    </div>

                    <div class="col-12 col-md-6">
                        <label for="id_m2_terreno" class="form-label">M2 Terreno</label>
                        <input type="text" class="form-control" id="id_m2_terreno" name="m2_terreno" value="{{form.m2_terreno.value}}">
                    </div>

                </div>
            </div>

            <div class="mb-3">

                <div class="row">

                    <div class="col-12 col-md-4">
                        <label for="id_cantidad_estacionamientos" class="form-label">Cantidad Estacionamientos</label>
                        <input type="text" class="form-control" id="id_cantidad_estacionamientos" name="cantidad_estacionamientos" value="{{form.cantidad_estacionamientos.value}}">
                    </div>

                    <div class="col-12 col-md-4">
                        <label for="id_cantidad_habitaciones" class="form-label">Cantidad Habitaciones</label>
                        <input type="text" class="form-control" id="id_cantidad_habitaciones" name="cantidad_habitaciones" value="{{form.cantidad_habitaciones.value}}">
                    </div>

                    <div class="col-12 col-md-4">
                        <label for="id_cantidad_banos" class="form-label">Cantidad Baños</label>
                        <input type="text" class="form-control" id="id_cantidad_banos" name="cantidad_banos" value="{{form.cantidad_banos.value}}">
                    </div>

                </div>

            </div>

            <div class="mb-3">

                <div class="row">

                    <div class="col-12 col-md-4">
                        <label for="id_tipo_de_inmueble" class="form-label">Tipo de Inmueble</label>
                        <select class="mb-3 form-select" aria-label="Tipo de Inmueble select" id="id_tipo_de_inmueble" name="tipo_de_inmueble">
                            <option selected>Tipo de Inmueble</option>
                            <option value="casa" {% if form.tipo_de_inmueble.value == 'casa' %} selected{% endif %}>Casa</option>
                            <option value="departamento"{% if form.tipo_de_inmueble.value == 'departamento' %} selected{% endif %}>Departamento</option>
                            <option value="parcela" {% if form.tipo_de_inmueble.value == 'parcela' %} selected{% endif %}>Parcela</option>
                        </select>
                    </div>

                    <div class="col-12 col-md-4">
                        <label for="id_precio" class="form-label">Precio</label>
                        <input type="text" class="form-control" id="id_precio" name="precio" value="{{form.precio.value}}">
                    </div>

                    <div class="col-12 col-md-4 form-check pt-5">
                        <input type="checkbox" class="form-check-input" id="id_disponible" name="disponible" {% if form.disponible.value %} checked{% endif %}>
                        <label class="form-check-label" for="id_disponible">Disponible</label>
                    </div>

                </div>

            </div>

            <div class="d-inline-flex">
                <button class="btn btn-primary" type="submit">Guardar Cambios</button>
                <a class="btn btn-secondary ms-4" href="{% url 'dashboard' %}">Volver</a>
            </div>

        </form>

    </div>

    {% comment %} <script>

        function getCookie(name) {

            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            //RETORNANDO EL TOKEN
            return cookieValue;

        }//end function getCookie

        function loadComunas() {
            event.preventDefault();
            let region_id = $('#region').val();
            let id = $('#id').val();
            let csrftoken = getCookie('csrftoken');
            if (region_id !== '0') {
                $.ajax({
                    type: 'POST',
                    url: $("#url").val(),
                    data: {csrfmiddlewaretoken: csrftoken,'region_id': region_id},
                    success: function (data) {
                    }
                });
            }
        }
    
    </script> {% endcomment %}

{% endblock %}

web/templates/perfil.html
{% extends 'base.html' %}

{% block content %}

    <fieldset class="bg-light py-4 my-5">

        <div class="text-center mb-3">
            <span class="d-inline-flex">
                <h2>Actualizar Datos</h2>
                <a class="btn btn-secondary ms-4" href="{% url 'dashboard' %}">Volver</a>
            </span>
        </div>

        <div class="col-2 col-md-4 mx-auto">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nombres">Nombres:</label>
                    <input type="text" class="form-control" id="id_nombres" name="nombres" value="{{ user.nombres }}" required>
                </div>
                <div class="form-group mt-3">
                    <label for="id_apellidos">Apellidos:</label>
                    <input type="text" class="form-control" id="id_apellidos" name="apellidos" value="{{ user.apellidos }}" required>
                </div>
                <div class="form-group mt-3">
                    <label for="id_correo_electronico">Correo electrónico:</label>
                    <input type="email" class="form-control" id="id_correo_electronico" name="correo_electronico" value="{{ user.correo_electronico }}" required>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Actualizar</button>
            </form>
        </div>

    </fieldset>

{% endblock %}

web/templates/registro_usuario.html
<!-- registro_usuario.html -->
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}
<div class="container">

    <div class="text-center my-4">
        <h2>Registrarse</h2>
    </div>

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" class="form-control" id="username" name="username" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_password">Password:</label>
            <input type="password" class="form-control" id="password" name="password" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" id="nombres" name="nombres" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" id="apellidos" name="apellidos" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_rut">Rut:</label>
            <input type="text" class="form-control" id="rut" name="rut" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_direccion">Direccion:</label>
            <input type="text" class="form-control" id="direccion" name="direccion" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_telefono">Telefono:</label>
            <input type="tel" class="form-control" id="telefono" name="telefono" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_correo_electronico">Correo electrónico:</label>
            <input type="email" class="form-control" id="correo_electronico" name="correo_electronico" required>
        </div>
        <div class="form-group mt-3">
            <label for="id_tipo_usuario">Tipo usuario:</label>
            <select class="form-control" id="tipo_usuario" name="tipo_usuario" required>
                <option value="arrendatario">Arrendatario</option>
                <option value="arrendador">Arrendador</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-4">Registrarse</button>
    </form>
</div>
{% endblock %}

web/templates/solicitudes_arrendador.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}
{% load static %}
{% block content %}
<h1>Solicitudes Recibidas</h1>
<ul>
    {% for solicitud in solicitudes %}
    <li>
        <p>Arrendatario: {{ solicitud.arrendatario }}</p>
        <p>Inmueble: {{ solicitud.inmueble }}</p>
        <p>Mensaje: {{ solicitud.mensaje }}</p>
    </li>
    {% empty %}
    <li>No hay solicitudes recibidas.</li>
    {% endfor %}
</ul>
   


{% endblock %}